### ISSUE TITLE
Kalogerone - Unsafe accounting threatens to break the mTBILL token peg to the IB01 price

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-05-midas-judging#159]
Kalogerone

high

# Unsafe accounting threatens to break the mTBILL token peg to the IB01 price

## Summary

In the [Midas docs](https://docs.midas.app/protocol-mechanics/mtbill-token) it is said that:

>1:1 Tracking: Each mTBILL token represents one share of the BlackRock Treasury Bond ([fund](https://www.blackrock.com/uk/individual/products/307243/ishares-treasury-bond-0-1yr-ucits-etf)) and is fully redeemable for the net asset value ([NAV](https://docs.midas.app/additional-topics/glossary#net-asset-value-nav)) of its representative amount.

Unsafe accounting in both the `DepositVault` and the `RedemptionVault` may break that promise and in case of a "bank-run" from users, its extremely possible someone will lose money.

This issue could potentially be very serious since the protocol is [regulated by the law](https://docs.midas.app/protocol-mechanics/legal-and-compliance/regulatory-compliance) and users who lose money due to the 1:1 not being true, could very easily use legal forces against the protocol.

## Vulnerability Detail

The issue arises from the fact that a user has the ability to `deposit` or `redeem` fractional shares but the protocol team can only buy or sell the IB01 in full shares off-chain. In the [IB01 ETF](https://www.blackrock.com/uk/individual/products/307243/ishares-treasury-bond-0-1yr-ucits-etf)'s official page (which is also linked in the Midas docs above) there is a [Prospectus pdf page](https://www.blackrock.com/uk/literature/prospectus/ishares-plc-prospectus-en.pdf) file, under article `(b) Title to Shares` it clearly states:

>(b) Title to Shares
....... **_Fractional Shares will not be issued._** .......

This is also confirmed with the protocol team through discord:

>A share costs $110.50. If you are asking to redeem half of a share, we would sell one entirely, and then keep $50 on the balance sheet not being $IB01.

This means that the protocol will almost always hold some value in USD which will not move with the IB01's price movements (which averages daily increases in price). This means in the long run or even in the short term if the protocol doesn't have a lot of users, the protocol faces the danger to not be able to fully back all the shares it has minted to the users.

**It's important to remember that historical price movements != future price movements. We want to cover all cases and make sure that the peg is safe at extreme price volatilities too.**

## Impact

Potential breakage of the 1:1 peg between the `mTBILL` token and the IB01. The protocol cant assure the peg due to having some balance in USD dollars which doesn't follow price fluctuations of the real shares. This is a broken peg, plus long run, the more price fluctuates of shares the bigger the loss will be for someone due to the intrinsically broken peg.

## Proof of Concept

Let's see the following scenario. Let's say 1 IB01 share = $100.

1. Bob deposits for 2.1 mTBILL tokens.
2. Protocol buys 3 IB01 shares and mints Bob 2.1 mTBILL tokens.
3. Alice deposits for 0.85 mTBILL tokens.
4. Protocol already has 0.9 IB01 shares remaining so they just mint Alice 0.85 mTBILL tokens.
5. Bob redeems all his 2.1 mTBILL tokens.
6. Protocol shares all 3 IB01 shares and pays Bob $210. Protocol has $90 left.
7. IB01 price goes to $110.
8. Alice redeems her 0.85 mTBILL tokens.
9. 0.85 * $110 = $93.5. Protocol has only $90 left and can't cover Alice's full withdrawal.

I know these numbers are very small compared to what the protocol will hold, but they are here to prove my point. Even if protocol loses 0.01% of the peg per year, in the long run it will be a big amount and **the legal impact will be huge and serious.**

## Code Snippet

[https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L91](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/DepositVault.sol#L91)
[https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/RedemptionVault.sol#L61](https://github.com/sherlock-audit/2024-05-midas/blob/main/midas-contracts/contracts/RedemptionVault.sol#L61)

## Tool used

Manual Review

## Recommendation

Rethink the `deposit` and `redeem` functions in `DepositVault.sol` and `RedemptionVault.sol`. 
Possibly use the IB01/USD data feed to only allow deposits and redeems of full shares.
The point is not to allow minting and redemptions of fractional shares, only full shares. You can calculate off-chain the full shares in every `deposit` and `redeem` and implement a refund function to send back the remaining money.

**Comment by Kalogerone** [comment]
Escalate 

Replying to the judges' comments:

> This is not a smart contract problem

How is a token which is supposed to be pegged to an off-chain value not a smart contract problem. If we were auditing a stablecoin and a finding was submitted that threatened its peg to the USD, would it be invalid? Also, the solution/recommendation is recommending a change to the code, so it's 100% a smart contract problem.

> this is always the case with any brokers && seems intended design in nature

1. I'm not sure if this is always the case, but we should improve when we can and fix any issues we can. Tokens lose their pegs all the time because "this is always the case with any brokers"
2. We are toking about the possibility of a token to lose its supposed peg. Don't believe protocol team has this intention in mind.

Additional info for the lead judge:

Please read the report carefully. The protocol is regulated by the law to be able to deliver what it promises. The codebase should be 100% safe regarding its token peg.

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> Replying to the judges' comments:
> 
> > This is not a smart contract problem
> 
> How is a token which is supposed to be pegged to an off-chain value not a smart contract problem. If we were auditing a stablecoin and a finding was submitted that threatened its peg to the USD, would it be invalid? Also, the solution/recommendation is recommending a change to the code, so it's 100% a smart contract problem.
> 
> > this is always the case with any brokers && seems intended design in nature
> 
> 1. I'm not sure if this is always the case, but we should improve when we can and fix any issues we can. Tokens lose their pegs all the time because "this is always the case with any brokers"
> 2. We are toking about the possibility of a token to lose its supposed peg. Don't believe protocol team has this intention in mind.
> 
> Additional info for the lead judge:
> 
> Please read the report carefully. The protocol is regulated by the law to be able to deliver what it promises. The codebase should be 100% safe regarding its token peg.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by IWildSniperI** [comment]
@Kalogerone so the problem here is that for any (web2) broker to operable he gives the ability to users buy and sell partial shares, although the shares are bought in whole for the broker, so the problem here is never driven from how smart contracts work but from how general brokers work and those problems are solved by high volume and fees to the protocol that gives them safe threshold to operate in that way

**Comment by CarlosAlegreUr** [comment]
> @Kalogerone so the problem here is that for any (web2) broker to operable he gives the ability to users buy and sell partial shares, although the shares are bought in whole for the broker, so the problem here is never driven from how smart contracts work but from how general brokers work and those problems are solved by high volume and fees to the protocol that gives them safe threshold to operate in that way

I dont remember that this protocol has fees. I do think this finding is valid, Im not sure if it is a High or a Medium but, there are real solutions related to the smart contract code, like allowing the team to lock an amount of extra value in the smart contract that covers that 0.01% part of the peg they cant assure due to the un-fractional (if that word exists) nature of the bonds.

Also the fact that this code and bussines are regulated by law which can allow affected users to report as a crime the losses is a serious consequence. On top of that, the possibility of being fixed but not can make it even more punishable. It is like if the team was informed of the problem and ignored it until someone got hurt, I think the crime is called: crime of negligence, which would increase the punishment enforced on the team if the affected victim reports the losses.

As it is actually an issue of how the real world asset and its properties are tokenized on the code, and because it can lose the peg, and because it can have legal consequences and it is actually fixable in the code. I do consider this a valid Medium or High issue.

**Comment by pronobis4** [comment]
Precisely because of what you wrote, I believe that this is not a "contract problem". The protocol ensures that it will be fair and allows you to buy "as much as you want", because everything is done offchain. There is no information that they will buy and sell bonds at the same time, only that they will keep them at the same price. This is how I understand it, which is why I agree that this is an off-chain problem and should be low.

**Comment by Kalogerone** [comment]
I would like address some misinformation on some of the comments above.
 
1. **_"There is no information that they will buy and sell bonds at the same time, only that they will keep them at the same price."_** 
There is information that they will buy and sell bonds at the same time. It is mentioned in the issue report above:
 
>This is also confirmed with the protocol team through discord:
A share costs $110.50. If you are asking to redeem half of a share, we would sell one entirely, and then keep $50 on the balance sheet not being $IB01.
 
2. Both of you, @IWildSniperI and @pronobis4 are making a lot of assumptions without any verified information from the protocol team, while I have presented direct comments made to me from them. You are both assuming that the protocol will handle this issue off-chain, through fees, through extra balance, etc...
 
3. **_"so the problem here is never driven from how smart contracts work but from how general brokers work and those problems are solved by high volume and fees to the protocol that gives them safe threshold to operate in that way"._** 
The problem literally exists because there are not some line of codes in the smart contracts to prevent this. The finding above is making 100% certain that the token will not lose its peg to the ETF through on-chain solidity code. The implementation of this code is simple and straight-forward. Don't allow orders of fractional shares.
 
_**Final author comments:**_
 
I respect you all of the commenters above for taking the time of your day to comment. I said on the discord that I was going to remove the escalation if the comments changed my mind but they didn't and I'm risking it. It just seems like the opinions are split and it's up to the Lead Judge now to decide. Good luck everyone on your next adventures!

**Comment by WangSecurity** [comment]
The question I have in mind is how do the users receive their tokens? As I see in the code mentioned in the report, both deposit and redeem functions take the tokens from the user (USDC they want to deposit or mTBILL they want to redeem), but the functions don't return anything. So where do the users receive their mTBILL after deposit and their USDC after redemption?

**Comment by Kalogerone** [comment]
It’s a very centralised system. As mentioned in their docs, whitelisted users that pass the KYC check have the ability to deposit and redeem as you said sending their tokens to the protocol. The protocol then reviews these transactions, which can take like 2 days, and then they send the promised tokens to the address which deposited or redeemed.

**Comment by WangSecurity** [comment]
Thank you, let's also take the following statement from the README into consideration:

> The conversion of USDC deposits to mTBILL tokens and vice-versa is performed offchain. These assets are bankruptcy protected, with attestation reports posted daily on the Midas site. This will be fully functional and working as intended. All reports are independently verified, and there should be no delays in reporting or posting the data.

Since, it's done off-chain and we don't know exactly how it will be converted and how many IB01 will be bought and how many mTBILL will users receive. Hence, I believe this off-chain system will prevent depeg or any problem about lost value.

Planning to reject the escalation and leave the issue as it is.

**Comment by Kalogerone** [comment]
We do know how this off-chain procedure will work, as I asked the sponsors and they answered me:

> A share costs $110.50. If you are asking to redeem half of a share, we would sell one entirely, and then keep $50 on the balance sheet not being $IB01.

This bit of info is also mentioned in my report above. They confirmed that they will hold USD in some cases, while the $IB01 price will be going up. My proof of case is a realistic representation of how the protocol will work, according to the dev team.

**Comment by WangSecurity** [comment]
But that's only the redemption and it's only a small part of the accounting system I believe. We don't know how this mechanism works exactly, yes, we have this little part, but that doesn't explain the entire conversion between USDC and mTBILL:

> Bob deposits for 2.1 mTBILL tokens.
Protocol buys 3 IB01 shares and mints Bob 2.1 mTBILL tokens.

We don't even know if that's true, maybe the protocol will buy only 3 IB01 shares? Hence, this is just an assumption that the off-chain mechanism allows for such discrepancies.

The decision remains the same, planning to reject the escalation and leave the issue as it is.

**Comment by Kalogerone** [comment]
_Making a final comment because I disagree and want to add something to your response. Won't make any more comments to allow the judging process to continue, don't want to be stubborn about it._

So we agree that the redemption will work like that because of the devs answer. The exact conversation went as follows:

Me:
> it has to do if you can buy fractional shares eg. 0.5 IB01 if a user requests only half the etf
and if yes whats the minimum you can get

Sponsor:
>A share costs $110.50. If you are asking to redeem half of a share, we would sell one entirely, and then keep $50 on the balance sheet not being $IB01.

My question was about the buying of the shares. The part you are not sure about. Sponsor just decided to give me redemption as an example. It would be safe to assume that this is the case for both deposits and redemptions, since my question on the depositing part didn't get any different clarification.

I just believe that if this issue was to get invalidated it would be because other reasons that I haven't thought of. To me it's pretty clear from my conversation with the dev team of how the protocol will work. And I also believe it's not healthy in such contests to make assumptions that the protocol have thought of this and will handle it off-chain. Thank you.

**Comment by WangSecurity** [comment]
Firstly, no need to repeat the same information again and again. If it was mentioned above, it's taken into consideration when making the decision.

Secondly, my answer is the same as above, we don't know how this calculation is made exactly, we only know that "bit of information" as you said. We don't know what formulas are used, what safety mechanisms are used and how it will be done in reality. 

> And I also believe it's not healthy in such contests to make assumptions that the protocol have thought of this and will handle it off-chain

I didn't say the sponsor has thought of this, I mean that we don't know how the off-chain mechanism works exactly. 

Hence, the decision remains the same, reject the escalation and leave the issue as it is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Kalogerone](https://github.com/sherlock-audit/2024-05-midas-judging/issues/159/#issuecomment-2156036675): rejected
